### ISSUE TITLE
Missing space in font causes rendering problems with pango: please consider adding a space glyph

### ISSUE THREAD

**Issue by mike-fabian** [OldHungarian/old-hungarian-font#1]
[rovas.txt](https://github.com/OldHungarian/old-hungarian-font/files/424936/rovas.txt)

![rovas](https://cloud.githubusercontent.com/assets/2330175/17774758/63929e5a-6555-11e6-8bdb-d10c918a8677.png)

The attached screenshot is created using  “pango-view  ~/rovas.txt” 

rovas.txt is also attached. It contains:

𐳀 𐳂
ع ى
א ב
a b

I.e. 4 lines with two characters and a space in between in each line.

The first line is Old Hungarian, the second line Arabic, the third line Hebrew and the fourth line
Latin.

In the screenshot one can see that pango renders the space between the two Old Hungarian
characters in the first line as a replacement character (A Box with the code point 0020 written
into the box). The reason  for this is that the Old Hungarian font (which I downloaded from this git
repository here) does  not contain a space. I am not sure whether that should be considered
a bug in pango or not (Should pango fall back to some other font to get a space??).

But the easiest fix is probably to add a space glyph to the font.

Having a space glyph is probably a good idea and might avoid more such rendering problems.

**Comment by mike-fabian** [comment]
Thank you for your quick fix,  it works!
![rovas](https://cloud.githubusercontent.com/assets/2330175/17777421/cc017550-6560-11e6-90fb-efcb5b290a77.png)

**Comment by sztupy** [comment]
Cool. Not sure if I have to include some additional commonly used characters, like punctuation marks or hyphens as well, or whether the fallback works fine there

**Comment by mike-fabian** [comment]
Zsolt Sz. Sztupák notifications@github.com さんは書きました:

> Cool. Not sure if I have to include some additional commonly used
> characters, like punctuation marks or hyphens as well, or whether the
> fallback works fine there

I have no idea at the moment either. I’ll tell you if I find something
during testing.

I found the problem with the missing space while testing an input method
I made for Old Hungarian:

https://github.com/mike-fabian/m17n-db-rovas

Recently I went to the Flock conference in Krakow, Poland. There I met
Zoltan Hoppar who told me about Old Hungarian and that we have no
easy way to input it on Fedora Linux. So I tried to make the above
input method and used your font to test.

## 

📧 Mike FABIAN   mike.fabian@gmx.de
睡眠不足はいい仕事の敵だ。

**Comment by sztupy** [comment]
Meanwhile I saw that adding the space character will most likely break web usage for the font, as it will override the main space character for the site for normal text as well. I might need to create two separate fonts, one with extra glyphs, and one without them

**Comment by sztupy** [comment]
Made a new version, with the two fonts separate. Can you try that your app still works with OldHungarian_Full?

**Comment by mike-fabian** [comment]
Zsolt Sz. Sztupák notifications@github.com さんは書きました:

> Made a new version, with the two fonts separate. Can you try that your app still works with OldHungarian_Full?

Yes, it works  with OldHungarian_Full!

## 

📧 Mike FABIAN   mike.fabian@gmx.de
睡眠不足はいい仕事の敵だ。

**Comment by mike-fabian** [comment]
Zsolt Sz. Sztupák notifications@github.com さんは書きました:

> Meanwhile I saw that adding the space character will most likely break
> web usage for the font, as it will override the main space character
> for the site for normal text as well. I might need to create two
> separate fonts, one with extra glyphs, and one without them

"most likely" or does it really break the web usage?

Doesn’t the space look the same in most fonts anyway?

I just thought it is confusing to have two different fonts and most
fonts have a space, also fonts for unusual languages.

For example, this Google font for Coptic also has a space:

https://noto-website.storage.googleapis.com/pkgs/NotoSansCoptic-unhinted.zip

## 

📧 Mike FABIAN   mike.fabian@gmx.de
睡眠不足はいい仕事の敵だ。

**Comment by sztupy** [comment]
One usage of the font is to supplement your normal font, as most fonts won't contain Old Hungarian. in this case if the font contains glyphs present in the original one it will override them, and having a different space looks quite ugly, unless it's exactly the same width as the one from the underlying font. Of course you could use this font only as a fallback font on the web, but in that case ligatures starts breaking in most browsers making contemporary usage difficult. And only using this font for Old Hungarian sections on your site is cumbersome, and might not work for user generated contents

**Comment by egmontkob** [comment]
See the pango issue here: https://gitlab.gnome.org/GNOME/pango/issues/273
