### ISSUE TITLE
Adding more ligatures

### ISSUE THREAD

**Issue by KrasnayaPloshchad** [OldHungarian/old-hungarian-font#2]
Old Hungarian employed a number of ligatures, but only small of them included in Unicode. As my propersal, you can adding rules to make letters produce ligature by inserting ZWJ between them, e.g. `𐲀[ZWJ]𐲂`, and making them available via `ccmp` feature.

**Comment by KrasnayaPloshchad** [comment]
Wikipedia has an example of them:
https://hu.wikipedia.org/wiki/F%C3%A1jl:Rovas_ligaturak.gif

**Comment by sztupy** [comment]
The fonts already support the mainly used contemporary ones (Dz, Dzs, Q, W, X, Y) using the ZWJ approach. I'm unsure which others are notable enough to be included additionally.

**Comment by KrasnayaPloshchad** [comment]
Yes, you're right. But I can't see you mentioned you have used the `ccmp` feature for them when I read the documentation.

**Comment by sztupy** [comment]
You can find them in https://github.com/OldHungarian/old-hungarian-font/blob/master/GLYPHS.md under the ligatures section. You can see it uses U+200D which is the ZWJ
